name: ARTenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - apptools=5.1.0=pyh44b312d_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.6.6=py39haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py39h196d8e1_0
  - beautifulsoup4=4.11.1=py39haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_0
  - bottleneck=1.3.4=py39h080aedc_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.0=py39h2bbff1b_1
  - chardet=4.0.0=py39haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py39h8cc25b3_0
  - configobj=5.0.6=py_0
  - console_shortcut=0.1.1=4
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=36.0.0=py39h21b164f_0
  - curl=7.79.1=h789b8ee_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.17.1=py39haa95532_1
  - double-conversion=3.2.0=h0e60522_0
  - eigen=3.4.0=h2d74725_0
  - entrypoints=0.4=py39haa95532_0
  - envisage=6.0.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.8=h39d44d4_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - gl2ps=1.4.2=h0597ee9_0
  - glew=2.1.0=h39d44d4_2
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_100
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=vc14hc45fdbb_0
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.11.4=py39hcbf5309_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - inflection=0.5.1=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py39haa95532_0
  - ipython=8.3.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jpeg=9e=h2bbff1b_0
  - jsoncpp=1.9.4=h2d74725_3
  - jsonschema=4.4.0=py39haa95532_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.4.0=py39haa95532_0
  - kiwisolver=1.3.2=py39hd77b12b_0
  - krb5=1.19.3=h1176d77_0
  - lazy-object-proxy=1.6.0=py39h2bbff1b_0
  - libcurl=7.79.1=h789b8ee_1
  - libflang=5.0.0=h6538335_20180525
  - libiconv=1.16=he774522_0
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.37=h2a8f88b_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.10.0=h680486a_2
  - libtheora=1.1.1=h8d14728_1005
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.12=hf5bbc77_0
  - libzip=1.8.0=hfed4ece_1
  - llvm-meta=5.0.0=0
  - loguru=0.6.0=py39hcbf5309_1
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib=3.5.1=py39haa95532_1
  - matplotlib-base=3.5.1=py39hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mayavi=4.7.2=py39h342a29d_5
  - mccabe=0.6.1=py39haa95532_1
  - menuinst=1.4.18=py39h59b6b97_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - mock=4.0.3=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39haa95532_1
  - nbclient=0.5.13=py39haa95532_0
  - nbconvert=6.4.4=py39haa95532_0
  - nbformat=5.3.0=py39haa95532_0
  - nest-asyncio=1.5.5=py39haa95532_0
  - numexpr=2.8.1=py39hb80d3ca_0
  - numpy=1.21.5=py39h7a0a035_2
  - numpy-base=1.21.5=py39hca35cd5_2
  - numpydoc=1.2=pyhd3eb1b0_0
  - openmp=5.0.0=vc14_1
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39hdc2b20a_0
  - pip=21.2.4=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - powershell_shortcut=0.0.1=3
  - poyo=0.5.0=pyhd3eb1b0_0
  - proj=6.2.1=ha7a8c7b_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py39h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py39h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyface=7.4.1=pyhd8ed1ab_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pylint=2.9.6=py39haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py39hbd8134f_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pysocks=1.7.1=py39haa95532_0
  - pytables=3.6.1=py39hbcfe41f_4
  - python=3.9.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py39h2bbff1b_2
  - pywin32-ctypes=0.2.0=py39haa95532_1000
  - pyyaml=6.0=py39h2bbff1b_1
  - pyzmq=22.3.0=py39hd77b12b_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - quaternion=2022.4.2=py39h5d4886f_0
  - regex=2022.3.15=py39h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py39h2eaa2aa_1
  - ruamel_yaml=0.15.100=py39h2bbff1b_0
  - scipy=1.7.3=py39h0a974cb_0
  - setuptools=61.2.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.4.0=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py39haa95532_1
  - spyder-kernels=2.1.3=py39haa95532_0
  - sqlite=3.38.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h2d74725_1
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.64.0=py39haa95532_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - traits=6.3.2=py39hb82d6ee_1
  - traitsui=7.3.1=pyhd8ed1ab_0
  - typed-ast=1.4.3=py39h2bbff1b_1
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - ujson=5.1.0=py39hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - utfcpp=3.2.1=h57928b3_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - vtk=9.0.3=py39h84a6d72_201
  - watchdog=2.1.6=py39haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - wrapt=1.12.1=py39h196d8e1_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.5=h04227a9_0
